name: Check for Bitrise Label

on:
  pull_request:
    types: [labeled, synchronize]

jobs:
  deploy:
    name: Trigger Build with Label
    runs-on: ubuntu-latest

    steps:
      - name: Get the pull request number
        id: pr_number
        run: |
          echo ::set-output name=number::$(echo "$GITHUB_REF" | awk -F / '{print $3}')
      - name: Send mobile build on bitrise
        if: contains(github.event.pull_request.labels.*.name, 'ready-for-qa')
        run: |
          echo "PR NUMBER: ${{ steps.pr_number.outputs.number }}"
